/**
 * Backend slop gate (query-time backstop).
 *
 * Content is rejected at first-index time by the Python pipeline
 * (search/filters/). This module is the second line of defence:
 * federated results from external providers are screened before
 * they ever reach the client.
 */

const DENY_DOMAINS = new Set([
  // Social platforms — user policy: never index/serve
  'facebook.com', 'fb.com', 'fb.watch', 'fbsbx.com',
  'instagram.com', 'cdninstagram.com',
  'tiktok.com',
  // AI content farms / AI writer marketing
  'aiwritershub.com', 'chatgptwriter.com', 'aicontentpro.com',
  'contentbot.ai', 'writesonic.com', 'jasper.ai',
  'rytr.me', 'copy.ai', 'peppertype.ai',
  // Essay mills / known spam
  'essaypro.com', 'essaywriter.net', 'cheapessay.net', 'grademiners.com',
  'studybay.com', 'speedyessay.com', 'essaybox.com', 'essayoneday.com',
  'penmypaper.com', 'papercoach.net', 'writemypapers.org',
]);

const AI_DISCLOSURE = [
  'as an ai language model',
  'as an ai assistant',
  'generated by chatgpt',
  'generated by ai',
  'written by an ai',
  'this article was generated',
  'this content was generated',
  'ai-generated article',
  'ai generated article',
];

const CLICKBAIT = [
  "you won't believe",
  'you wont believe',
  'shocking truth',
  'doctors hate',
  'one weird trick',
  'this one trick',
  'gone wrong',
  'gone sexual',
  'must watch before',
  'nobody talks about',
];

export function domainOf(url: string): string {
  try {
    return new URL(url).hostname.toLowerCase().replace(/^www\./, '');
  } catch {
    return '';
  }
}

export function isBlockedDomain(url: string): boolean {
  const domain = domainOf(url);
  if (!domain) return false;
  for (const denied of DENY_DOMAINS) {
    if (domain === denied || domain.endsWith('.' + denied)) return true;
  }
  return false;
}

export function hasAiDisclosure(text: string): boolean {
  const t = (text || '').toLowerCase();
  return AI_DISCLOSURE.some(p => t.includes(p));
}

export function clickbaitPenalty(title: string): number {
  const t = (title || '').toLowerCase();
  return CLICKBAIT.some(p => t.includes(p)) ? 0.5 : 0;
}

export function isClickbait(title: string): boolean {
  const t = (title || '').toLowerCase();
  return CLICKBAIT.some(p => t.includes(p));
}

/** Multiplier in (0, 1]: 1 = clean, 0 = dropped by the hard gate. */
export function slopPenalty(result: { url?: string; title?: string; snippet?: string; provider?: string }): number {
  if (result.url && isBlockedDomain(result.url)) return 0;
  if (result.title && hasAiDisclosure(result.title)) return 0;
  if (result.snippet && hasAiDisclosure(result.snippet)) return 0;
  if (isClickbait(result.title || '')) return 0;
  return 1;
}

/** Hard gate: drops blocked/AI/clickbait results entirely. */
export function screenResults<T extends { url: string; title?: string; snippet?: string; provider?: string }>(items: T[]): T[] {
  const seen = new Set<string>();
  const kept: T[] = [];

  for (const item of items) {
    if (!item.url || isBlockedDomain(item.url)) continue;
    if (item.title && hasAiDisclosure(item.title)) continue;
    if (item.snippet && hasAiDisclosure(item.snippet)) continue;
    if (item.title && isClickbait(item.title)) continue;

    const key = normalizeUrlKey(item.url);
    if (seen.has(key)) continue;
    seen.add(key);
    kept.push(item);
  }

  return kept;
}

export function normalizeUrlKey(url: string): string {
  try {
    const u = new URL(url);
    return (u.hostname.toLowerCase().replace(/^www\./, '') + u.pathname.replace(/\/+$/, '')).toLowerCase();
  } catch {
    return url.toLowerCase();
  }
}

export { DENY_DOMAINS, AI_DISCLOSURE, CLICKBAIT };
